services:
  backend:
    build: .
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres3:1234561@db:5432/bancoestudo2?schema=public"
      BACKEND_PORT: 3000

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres3
      POSTGRES_PASSWORD: 1234561
      POSTGRES_DB: bancoestudo2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:  
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres3 -d bancoestudo2"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
